name: Build Mega Drive ROM

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build SGDK ROM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ROM (Docker SGDK)
        run: docker run --rm -v $PWD:/m68k -t registry.gitlab.com/doragasu/docker-sgdk:v2.00

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: out-drive-rom
          path: out/rom.bin
          if-no-files-found: error
